version: '3'

services:
  app:
    image: edouardberthe/remindmeal:test
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - net
  db:
    image: postgres:alpine
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_USER: remindmeal
      POSTGRES_PASSWORD: remindmeal
      POSTGRES_DB: remindmeal

volumes:
  data:

networks:
  net:
