version: '3'

services:
  app:
    image: remindmeal/remindmeal:latest
    ports:
      - 9001:80
    networks: 
      - net
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  db:
    image: postgres:13
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net
    env_file:
      - .env

volumes:
  data:

networks:
  net:
