version: '3'

services:
  app:
    image: remindmeal/remindmeal:latest
    ports:
      - 9001:80
    networks: 
      - net
    depends_on:
      - db
  db:
    image: postgres:11.6-alpine
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_USER: remindmeal
      POSTGRES_PASSWORD: remindmeal
      POSTGRES_DB: remindmeal

volumes:
  data:

networks:
  net:
