name: .NET Core

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      
      - name: Release Build
        run: dotnet build --configuration Release src/RemindMeal.csproj

      - name: Debug Build
        run: dotnet build --configuration Release src/RemindMeal.csproj

      - name: Launch tests
        run: dotnet test

  push:
    name: Docker Push
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build & Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: remindmeal/remindmeal
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ./docker/
          context: ./
